In [2]:
import gym

# MuJoCo
Continuous control tasks, running in a fast physics simulator.

* **Ant-v2**
  * observation_space: **Box(111,)**
  * action_space: **Box(8,)**
* **HalfCheetah-v2**
  * observation_space: **Box(17,)**
  * action_space: **Box(6,)**
* **Hopper-v2**
  * observation_space:**Box(11,)**
  * action_space: **Box(3,)**
* **Humanoid-v2**
  * observation_space: **Box(376,)**
  * action_space: **Box(17,)**
* **HumanoidStandup-v2**
  * observation_space: **Box(376,)**
  * action_space: **Box(17,)**
* **InvertedDoublePendulum-v2**
  * observation_space: **Box(11,)**
  * action_space: **Box(1,)**
* **InvertedPendulum-v2**
  * observation_space: **Box(4,)**
  * action_space: **Box(1,)**
* **Reacher-v2**
  * observation_space: **Box(11,)**
  * action_space: **Box(2,)**
* **Swimmer-v2**
  * observation_space: **Box(8,)**
  * action_space: **Box(2,)**
* **Walker2d-v2**
  * observation_space: **Box(17,)**
  * action_space: **Box(6,)**

In [22]:
MuJoCo_env_names = ['Ant-v2', 'HalfCheetah-v2', 'Hopper-v2', 'Humanoid-v2', 
                    'HumanoidStandup-v2', 'InvertedDoublePendulum-v2', 'InvertedPendulum-v2', 'Reacher-v2',
                    'Swimmer-v2', 'Walker2d-v2']
action_dims = []
for env_name in MuJoCo_env_names:
    env = gym.make(env_name)
    print('Environment: {}'.format(env_name))
    print('observation_space: {}'.format(env.observation_space))
    print('action_space: {}'.format(env.action_space))
    action_dims.append(env.action_space.shape[0])

import numpy as np
action_dims = np.array(action_dims)
np.unique(action_dims)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: Ant-v2
observation_space: Box(111,)
action_space: Box(8,)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: HalfCheetah-v2
observation_space: Box(17,)
action_space: Box(6,)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: Hopper-v2
observation_space: Box(11,)
action_space: Box(3,)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide ex

array([ 1,  2,  3,  6,  8, 17])

# Box2D
Continuous control tasks in the Box2D simulator.


In [4]:
Box2D_env_names = ['BipedalWalker-v2', 'BipedalWalkerHardcore-v2', 'CarRacing-v0', 
                   'LunarLander-v2', 'LunarLanderContinuous-v2']
for env_name in Box2D_env_names:
    env = gym.make(env_name)
    print('Environment: {}'.format(env_name))
    print('observation_space: {}'.format(env.observation_space))
    print('action_space: {}'.format(env.action_space))

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: BipedalWalker-v2
observation_space: Box(24,)
action_space: Box(4,)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: BipedalWalkerHardcore-v2
observation_space: Box(24,)
action_space: Box(4,)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: CarRacing-v0
observation_space: Box(96, 96, 3)
action_space: Box(3,)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: LunarLander-v2
observation_space: Box(8,)
action_space: Discrete(4)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please 

# Atari
Reach high scores in Atari 2600 games.

all actions are discrete.

In [19]:

Atari_env_names = ['AirRaid-ram-v0', 'AirRaid-v0', 'Alien-ram-v0', 
                   'Alien-v0', 'Amidar-ram-v0', 'Amidar-v0', 
                   'Assault-ram-v0', 'Assault-v0', 'Asterix-ram-v0', 
                   'Asterix-v0', 'Asteroids-ram-v0', 'Asteroids-v0', 
                   'Atlantis-ram-v0', 'Atlantis-v0', 'BankHeist-ram-v0', 
                   'BankHeist-v0', 'BattleZone-ram-v0', 'BattleZone-v0', 
                   'BeamRider-ram-v0', 'BeamRider-v0', 'Berzerk-ram-v0', 
                   'Berzerk-v0', 'Bowling-ram-v0', 'Bowling-v0', 
                   'Boxing-ram-v0', 'Boxing-v0','Breakout-ram-v0',
                   'Breakout-v0','Carnival-ram-v0','Carnival-v0',
                   'Centipede-ram-v0','Centipede-v0','ChopperCommand-ram-v0',
                   'ChopperCommand-v0','CrazyClimber-ram-v0','CrazyClimber-v0',
                   'DemonAttack-ram-v0','DemonAttack-v0','DoubleDunk-ram-v0',
                   'DoubleDunk-v0','ElevatorAction-ram-v0','ElevatorAction-v0',
                   'Enduro-ram-v0','Enduro-v0','FishingDerby-ram-v0',
                   'FishingDerby-v0','Freeway-ram-v0','Freeway-v0', 
                   'Frostbite-ram-v0', 'Frostbite-v0', 'Gopher-ram-v0',
                   'Gopher-v0', 'Gravitar-ram-v0', 'Gravitar-v0',
                   'IceHockey-ram-v0', 'IceHockey-v0', 'Jamesbond-ram-v0',
                   'Jamesbond-v0', 'JourneyEscape-ram-v0', 'JourneyEscape-v0',
                   'Kangaroo-ram-v0', 'Kangaroo-v0', 'Krull-ram-v0',
                   'Krull-v0', 'KungFuMaster-ram-v0', 'KungFuMaster-v0',
                   'MontezumaRevenge-ram-v0', 'MontezumaRevenge-v0', 'MsPacman-ram-v0',
                   'MsPacman-v0', 'NameThisGame-ram-v0', 'NameThisGame-v0',
                   'Phoenix-ram-v0', 'Phoenix-v0', 'Pitfall-ram-v0',
                   'Pitfall-v0', 'Pong-ram-v0', 'Pong-v0', 
                   'Pooyan-ram-v0', 'Pooyan-v0', 'PrivateEye-ram-v0',
                   'PrivateEye-v0', 'Qbert-ram-v0', 'Qbert-v0',
                   'Riverraid-ram-v0', 'Riverraid-v0', 'RoadRunner-ram-v0',
                   'RoadRunner-v0', 'Robotank-ram-v0', 'Robotank-v0',
                   'Seaquest-ram-v0', 'Seaquest-v0', 'Skiing-ram-v0',
                   'Skiing-v0', 'Solaris-ram-v0', 'Solaris-v0',
                   'SpaceInvaders-ram-v0', 'SpaceInvaders-v0', 'StarGunner-ram-v0',
                   'StarGunner-v0', 'Tennis-ram-v0', 'Tennis-v0',
                   'TimePilot-ram-v0', 'TimePilot-v0', 'Tutankham-ram-v0',
                   'Tutankham-v0', 'UpNDown-ram-v0', 'UpNDown-v0',
                   'Venture-ram-v0', 'Venture-v0', 'VideoPinball-ram-v0',
                   'VideoPinball-v0', 'WizardOfWor-ram-v0', 'WizardOfWor-v0',
                   'YarsRevenge-ram-v0', 'YarsRevenge-v0', 'Zaxxon-ram-v0',
                   'Zaxxon-v0']
action_dims = []
for env_name in Atari_env_names:
    env = gym.make(env_name)
    print('Environment: {}'.format(env_name))
    print('observation_space: {}'.format(env.observation_space))
    print('action_space: {}'.format(env.action_space))
    action_dims.append(env.action_space.n)


Environment: AirRaid-ram-v0
observation_space: Box(128,)
action_space: Discrete(6)
Environment: AirRaid-v0
observation_space: Box(250, 160, 3)
action_space: Discrete(6)
Environment: Alien-ram-v0
observation_space: Box(128,)
action_space: Discrete(18)
Environment: Alien-v0
observation_space: Box(210, 160, 3)
action_space: Discrete(18)
Environment: Amidar-ram-v0
observation_space: Box(128,)
action_space: Discrete(10)
Environment: Amidar-v0
observation_space: Box(250, 160, 3)
action_space: Discrete(10)
Environment: Assault-ram-v0
observation_space: Box(128,)
action_space: Discrete(7)
Environment: Assault-v0
observation_space: Box(250, 160, 3)
action_space: Discrete(7)
Environment: Asterix-ram-v0
observation_space: Box(128,)
action_space: Discrete(9)
Environment: Asterix-v0
observation_space: Box(210, 160, 3)
action_space: Discrete(9)
Environment: Asteroids-ram-v0
observation_space: Box(128,)
action_space: Discrete(14)
Environment: Asteroids-v0
observation_space: Box(210, 160, 3)
action_sp

Environment: SpaceInvaders-ram-v0
observation_space: Box(128,)
action_space: Discrete(6)
Environment: SpaceInvaders-v0
observation_space: Box(210, 160, 3)
action_space: Discrete(6)
Environment: StarGunner-ram-v0
observation_space: Box(128,)
action_space: Discrete(18)
Environment: StarGunner-v0
observation_space: Box(210, 160, 3)
action_space: Discrete(18)
Environment: Tennis-ram-v0
observation_space: Box(128,)
action_space: Discrete(18)
Environment: Tennis-v0
observation_space: Box(250, 160, 3)
action_space: Discrete(18)
Environment: TimePilot-ram-v0
observation_space: Box(128,)
action_space: Discrete(10)
Environment: TimePilot-v0
observation_space: Box(210, 160, 3)
action_space: Discrete(10)
Environment: Tutankham-ram-v0
observation_space: Box(128,)
action_space: Discrete(8)
Environment: Tutankham-v0
observation_space: Box(250, 160, 3)
action_space: Discrete(8)
Environment: UpNDown-ram-v0
observation_space: Box(128,)
action_space: Discrete(6)
Environment: UpNDown-v0
observation_space:

In [20]:
import numpy as np
action_dims = np.array(action_dims)
np.unique(action_dims)

array([ 3,  4,  6,  7,  8,  9, 10, 14, 16, 18])

# Classic control
Control theory problems from the classic RL literature.

* **Acrobot-v1**:
   * observation_space: **Box(6,)**
   * action_space: **Discrete(3)**
* **CartPole-v1**:
   * observation_space: **Box(4,)**
   * action_space: **Discrete(2)**
* **MountainCar-v0**:
   * observation_space: **Box(2,)**
   * action_space: **Discrete(3)**
* **MountainCarContinuous-v0**:
   * observation_space: **Box(2,)**
   * action_space: **Box(1,)**
* **Pendulum-v0**:
   * observation_space: **Box(3,)**
   * action_space: **Box(1,)**


In [6]:
Classic_control_env_names = ['Acrobot-v1', 'CartPole-v1', 'MountainCar-v0', 
                             'MountainCarContinuous-v0', 'Pendulum-v0']
for env_name in Classic_control_env_names:
    env = gym.make(env_name)
    print('Environment: {}'.format(env_name))
    print('observation_space: {}'.format(env.observation_space))
    print('action_space: {}'.format(env.action_space))

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: Acrobot-v1
observation_space: Box(6,)
action_space: Discrete(3)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: CartPole-v1
observation_space: Box(4,)
action_space: Discrete(2)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: MountainCar-v0
observation_space: Box(2,)
action_space: Discrete(3)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: MountainCarContinuous-v0
observation_space: Box(2,)
action_space: Box(1,)
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide 

# Test

In [23]:
env_name = 'Ant-v2'
# env_name = 'CartPole-v1'
env = gym.make(env_name)
print('Environment: {}'.format(env_name))
print('observation_space: {}'.format(env.observation_space))
print('action_space: {}'.format(env.action_space))

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Environment: Ant-v2
observation_space: Box(111,)
action_space: Box(8,)


In [24]:
from gym import envs
len(envs.registry.all())

797

In [26]:
env.sample()

AttributeError: 'TimeLimit' object has no attribute 'sample'

In [25]:
env.action_space.n

AttributeError: 'Box' object has no attribute 'n'

In [10]:
env.reset()

array([-0.04730155,  0.01841479,  0.03809119,  0.00383959])

In [11]:
env.step(0)

(array([-0.04693326, -0.17723215,  0.03816798,  0.30829323]), 1.0, False, {})